name: Deploy to cPanel
on:
  push:
    branches: [main]
jobs:
  FTP-Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.5
        with:
          server: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          protocol: ftp
          secure: true
          server-dir: ./public_html/
          security-mode: loose
