name: Deploy to FTP
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to FTP
    runs-on: Ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@master
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /
          exclude: |
            LICENSE
            README.md
            .git
          protocol: ftps
