name: Deploy to FTP
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to FTP
    runs-on: Ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@master
        with:
          server: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          local_dir: .
          remote_dir: /
          exclude: |
            README.md
            LICENSE
          delete: false
          protocol: ftps
